### ISSUE TITLE
HappyChat global can chat is string, but should be a boolean

### ISSUE THREAD

**Issue by dwainm** [Automattic/happychat-client#201] opened 2018-04-10 15:38 UTC
The global value coming from happychat-client wp target is: “canChat”: “true” [string]

You can see this in: 
`happychatSettings.canChat`

When you filter and set it to `true`[bool] it is converted to “1” by the plugin.

HappyChat is expecting a bool:
https://github.com/Automattic/happychat-client/blob/master/src/index.js#L170-L180

**Comment by nosolosw** [comment] 2018-04-27 16:20
Hey @dwainm - so the flow for passing the settings is like this: 

- the PHP plugin passes the `happychat_settings` array to the client using the [wp_localize_script](https://developer.wordpress.org/reference/functions/wp_localize_script/) method. Everything is a string in that object because AFAIK `wp_localize_script` can only take strings in the data array. So, in PHP land, the `canChat` properties need to be defined as strings in the `happychat_settings` filter.
- upon receiving the settings, the client converts the `canChat` properties from String to Boolean using the [toBoolean](https://github.com/Automattic/happychat-client/blob/master/targets/wordpress/assets/client-happychat-init.js#L12) function (both for the global `canChat` property and recursively for the `canChat` properties that can be assigned in the menu options).
- internally, Happychat [does use booleans](https://github.com/Automattic/happychat-client/blob/master/src/index.js#L170-L180) as you mentioned.

So I've checked this flow for the global `canChat` property and is working properly. Could you give me specific steps to reproduce the bug you experienced?

**Comment by dwainm** [comment] 2018-04-27 17:43
@nosolosw I saw that you did the conversion on the client side before passing it to HC. 

`wp_localize_script` does accept booleans. See the output on the terminal below ( the global `string` vs the item list `bool` )

<img width="367" alt="screen shot 2018-04-27 at 19 40 08" src="https://user-images.githubusercontent.com/1713474/39376769-1e398258-4a53-11e8-9cc3-b6b135ab49dc.png">

**Comment by dwainm** [comment] 2018-04-27 17:43
So no conversion is needed before passing it to HC.

**Comment by nosolosw** [comment] 2018-04-30 11:15
This is an inconsistency with `wp_localize_string`, well summarized in this core ticket https://core.trac.wordpress.org/ticket/43766. TLDR: any scalar values are cast to String, but it doesn't happen recursively, so scalars within arrays won't be cast. That's the reason the global canChat property is converted to "1" when passed as a boolean but the entryOptions's canChat stay booleans.

There is some ongoing work to fix this in core https://core.trac.wordpress.org/ticket/25280 but it hasn't landed yet. For consistency, I think all `canChat` properties here should be passed as strings.

**Closed by nosolosw** 2018-04-30 11:15 UTC
Labels: [Target] WordPress, [Type] Bug
