### ISSUE TITLE
SelectDropdown contents are hidden by iframe

### ISSUE THREAD

**Issue by oandregal** [Automattic/happychat-client#240] opened 2018-06-25 12:24 UTC
When a SelectDropdown contains a lot of items and it's open, depending on the number of items and the iframe height the drop-down may be cut off.

**Comment by dwainm** [comment] 2018-08-23 13:28
Something to add here is that the whole page seems to be hidden on Woo.com on Safari and Firefox:
https://woocommerce.com/my-account/create-a-ticket/

You need a Woo.com user account to see it ( can log in with WP.com account ).

**Comment by nosolosw** [comment] 2018-08-24 08:35
@dwainm I've just checked and it works for me in Firefox. I can't test Safari. Can you reproduce? If so, that merits a different issue and we should address that immediately. Please, do ping me there.

**Comment by dwainm** [comment] 2018-09-03 06:17
@nosolosw this is fixed in the latest version.

**Comment by rwaynick** [comment] 2018-11-02 16:59
WooCommerce.com user in 1348563-hc was frustrated with this issue and didn't understand that this was a search box. Instead they choose "Storefront" which was at the bottom of the drop-down list and thus they got chat instead of the ticket form for an extension that was at the bottom of the list "WooCommerce Product Search". i.e., they were expecting to be able to scroll.

<img width="435" alt="screen shot 2018-11-02 at 12 48 48 pm" src="https://user-images.githubusercontent.com/10882502/47929349-1fd4b480-de9f-11e8-93d6-a72de38c397b.png">

**Comment by gedex** [comment] 2019-01-14 16:00
@nosolosw any updates on this? Got similar issue as reported by @rwaynick.

**Comment by nosolosw** [comment] 2019-01-15 08:30
No progress that I know of. I'm no longer involved with this project, so I may be missing context on current work being done.

**Closed** 2024-12-18 10:08 UTC
Labels: [Type] Bug, Needs Design, [Target] Core, [Component] iframe
